# Generated by Django 3.2.7 on 2021-10-05 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='Room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chat_app.Room'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='message',
            name='value',
            field=models.CharField(blank=True, max_length=100000),
        ),
        migrations.AlterField(
            model_name='Room',
            name='name',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
